steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'VITE_API_URL=https://japa-backend-11121208510.us-central1.run.app/api'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/japa-frontend'
      - .
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/japa-frontend'
